# Generated by Django 4.0.4 on 2022-05-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('letter', models.JSONField(null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('is_integral', models.IntegerField(null=True)),
                ('is_open_enroll', models.IntegerField(null=True)),
                ('is_open_edit', models.IntegerField(null=True)),
                ('is_open_document', models.IntegerField(null=True)),
                ('is_open_estimate', models.IntegerField(null=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'competition',
            },
        ),
    ]
