# Generated by Django 4.0.4 on 2022-05-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.IntegerField()),
                ('schedule_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('number', models.SmallIntegerField(null=True)),
                ('order', models.SmallIntegerField(null=True)),
                ('city', models.CharField(max_length=10, null=True)),
                ('agency', models.CharField(max_length=50, null=True)),
                ('level', models.CharField(max_length=50, null=True)),
                ('group', models.CharField(max_length=50, null=True)),
                ('item', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('coach', models.CharField(max_length=30, null=True)),
                ('leader', models.CharField(max_length=30, null=True)),
                ('manager', models.CharField(max_length=30, null=True)),
                ('director', models.CharField(max_length=30, null=True)),
                ('sound', models.CharField(max_length=100, null=True)),
                ('check_in_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enrolls',
            },
        ),
    ]
