# Generated by Django 4.0.4 on 2022-05-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
