# Generated by Django 4.0.4 on 2022-04-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_payment_rename_enrolls_enroll'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
    ]
