# Generated by Django 4.0.4 on 2022-05-08 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_player_identity'),
        ('enroll', '0002_enroll_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player'),
        ),
    ]
