# Generated by Django 4.0.4 on 2022-04-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_alter_payment_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
