# Generated by Django 4.0.4 on 2022-05-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_alter_enroll_player_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='player_id',
            new_name='player',
        ),
    ]
