# Generated by Django 4.0.4 on 2022-04-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=60)),
                ('team_id', models.IntegerField(null=True)),
                ('identity', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('city', models.CharField(max_length=10, null=True)),
                ('agency', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('role', models.IntegerField(null=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remember_token', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
